require('dotenv').config();
const fs=require('node:fs');const path=require('node:path');const http=require('node:http');const express=require('express');const pino=require('pino');const {default:makeWASocket,Browsers,useMultiFileAuthState,DisconnectReason,downloadContentFromMessage,jidDecode}=require('@musteqeem/baileys');const {Boom}=require('@hapi/boom');
const {JsonStore}=require('./src/store/jsonStore');const {CommandRegistry}=require('./src/core/commandRegistry');const {DefenseEngine}=require('./src/core/defenseEngine');
const PORT=Number(process.env.PORT||3000),SESSION=path.resolve(process.env.SESSION_DIR||'sessions'),PHONE=String(process.env.PAIRING_PHONE||'').replace(/\D/g,'');
const app=express();const server=http.createServer(app);let sock=null;let reconnectTimer=null;let attempts=0;let shutting=false;let registry=new CommandRegistry();const store=new JsonStore();const defense=new DefenseEngine(store);registry.load();
app.get('/',(_q,r)=>r.json({name:'NODAX',status:'online',commands:registry.commands.length}));app.get('/health',(_q,r)=>r.json({ok:true,connected:Boolean(sock?.user),commands:registry.commands.length,uptime:process.uptime()}));server.listen(PORT,'0.0.0.0',()=>console.log(`[web] NODAX health on ${PORT}`));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));const norm=j=>{if(!j||!j.includes(':'))return j;const d=jidDecode(j);return d?.user&&d?.server?`${d.user}@${d.server}`:j};const owner=j=>String(process.env.OWNER_NUMBERS||'').split(',').map(x=>x.replace(/\D/g,'')).includes(String(j).split('@')[0].split(':')[0]);
async function context(m,s){const jid=m.key.remoteJid,sender=norm(m.key.participant||jid),raw=m.message||{};const text=String(raw.conversation||raw.extendedTextMessage?.text||raw.imageMessage?.caption||raw.videoMessage?.caption||'').trim();const quotedRaw=raw.extendedTextMessage?.contextInfo?.quotedMessage;const quotedSender=raw.extendedTextMessage?.contextInfo?.participant;let metadata=null,isAdmin=owner(sender),isBotAdmin=false;if(jid.endsWith('@g.us')){metadata=await s.groupMetadata(jid);const me=norm(s.user?.id);const p=metadata.participants.find(x=>norm(x.id)===sender),b=metadata.participants.find(x=>norm(x.id)===me||x.id?.startsWith(s.user?.id?.split(':')[0]));isAdmin=isAdmin||['admin','superadmin'].includes(p?.admin);isBotAdmin=['admin','superadmin'].includes(b?.admin)}return {raw:m,chat:jid,sender,text,isGroup:jid.endsWith('@g.us'),metadata,isAdmin,isBotAdmin,mentionedJid:raw.extendedTextMessage?.contextInfo?.mentionedJid||[],quoted:quotedRaw?{raw:{key:{remoteJid:jid,participant:quotedSender,message:quotedRaw},message:quotedRaw},sender:quotedSender,text:String(quotedRaw.conversation||quotedRaw.extendedTextMessage?.text||'')}:null};}
async function execute(cmd,m,args){if(cmd.groupOnly&&!m.isGroup)return m.reply('❌ This command only works in a group.');if(cmd.ownerOnly&&!owner(m.sender))return m.reply('❌ Owner-only command.');if(cmd.adminOnly&&!m.isAdmin)return m.reply('❌ Group-admin permission required.');if(cmd.botAdmin&&!m.isBotAdmin)return m.reply('❌ Make NODAX a group admin first.');return cmd.execute(sock,m,{args,reply:m.reply,store,registry,defense});}
async function handle(raw){if(!raw?.key?.remoteJid||raw.key.fromMe)return;const m=await context(raw,sock);m.reply=async(content,extra={})=>sock.sendMessage(m.chat,typeof content==='string'?{text:content,...extra}:content,{quoted:m.raw});if(!m.text)return;const violation=await defense.inspect(sock,m);if(violation){await m.reply(violation,{mentions:[m.sender]});return}const prefix=process.env.PREFIX||'.';if(!m.text.startsWith(prefix))return;const body=m.text.slice(prefix.length).trim();const [name,...args]=body.split(/\s+/);const cmd=registry.resolve(name);if(!cmd)return m.reply(`❌ Unknown command *${name}*. Use ${prefix}help.`);try{await m.reply(`⏳ ${cmd.name} is working...`);await execute(cmd,m,args)}catch(e){console.error(`[${cmd.name}]`,e);await m.reply(`❌ ${cmd.name} failed: ${e.message}`)}}
function clearReconnect(){if(reconnectTimer)clearTimeout(reconnectTimer);reconnectTimer=null}
function schedule(reason){if(shutting||reconnectTimer)return;attempts++;const wait=Math.min(120000,5000*2**Math.min(attempts-1,5));console.log(`[connection] ${reason}; retry in ${Math.ceil(wait/1000)}s`);reconnectTimer=setTimeout(()=>{reconnectTimer=null;connect().catch(e=>schedule(e.message))},wait)}
async function closeSocket(s){try{s?.ws?.close?.()}catch{}try{await s?.end?.()}catch{}}
async function connect(){if(shutting||sock)return;fs.mkdirSync(SESSION,{recursive:true});const {state,saveCreds}=await useMultiFileAuthState(SESSION);let requested=false;const current=makeWASocket({logger:pino({level:process.env.LOG_LEVEL||'silent'}),auth:state,browser:Browsers.macOS('Chrome'),connectTimeoutMs:60000,defaultQueryTimeoutMs:60000,keepAliveIntervalMs:30000,markOnlineOnConnect:false,printQRInTerminal:false});current.downloadContentFromMessage=downloadContentFromMessage;sock=current;current.ev.on('creds.update',saveCreds);current.ev.on('connection.update',async u=>{if(current!==sock)return;if(!state.creds.registered&&!PHONE&&!requested){requested=true;console.error('[pairing] Set PAIRING_PHONE in .env; QR login is disabled.')}if(!state.creds.registered&&PHONE&&!requested&&(u.connection==='connecting'||u.qr)){requested=true;try{console.log(`[pairing] code: ${await current.requestPairingCode(PHONE)}`)}catch(e){requested=false;console.error('[pairing]',e.message)}}if(u.connection==='open'){attempts=0;console.log(`[connection] NODAX online as ${current.user?.id}`)}if(u.connection==='close'){sock=null;const code=u.lastDisconnect?.error?.output?.statusCode||new Boom(u.lastDisconnect?.error||{}).output?.statusCode;console.log('[connection] closed',code);if(code===DisconnectReason.loggedOut||code===DisconnectReason.connectionReplaced)return;await closeSocket(current);schedule('transient disconnect')}});current.ev.on('group-participants.update',async u=>{try{if(!['add','remove'].includes(u.action))return;const g=store.group(u.id);if((u.action==='add'&&!g.welcome)||(u.action==='remove'&&!g.goodbye))return;const meta=await current.groupMetadata(u.id);for(const p0 of u.participants||[]){const p=typeof p0==='string'?p0:p0.id;const text=(u.action==='add'?g.welcomeText||'Welcome @user to @group!':g.goodbyeText||'Goodbye @user.').replaceAll('@user',`@${p.split('@')[0]}`).replaceAll('@group',meta.subject).replaceAll('@count',String(meta.participants.length));await current.sendMessage(u.id,{text,mentions:[p]})}}catch(e){console.error('[group event]',e.message)}});current.ev.on('messages.upsert',async({messages})=>{for(const x of messages)await handle(x).catch(e=>console.error('[message]',e.message))})}
async function shutdown(sig){shutting=true;clearReconnect();await closeSocket(sock);server.close();console.log('[shutdown]',sig);process.exit(0)}process.once('SIGINT',()=>shutdown('SIGINT'));process.once('SIGTERM',()=>shutdown('SIGTERM'));process.on('unhandledRejection',e=>console.error('[unhandled]',e));connect().catch(e=>{sock=null;console.error('[startup]',e.message);schedule('startup failure')});
