const {inputText}=require('../../core/helpers');
function make(name,text){return {name,category:'Education',desc:`${name} study tool`,usage:`.${name} [topic]`,execute:async(s,m,{args,reply})=>reply(`📘 ${name.toUpperCase()}\n\n${text}${args.length?`\n\nTopic: ${inputText(args,m)}`:''}`)}}
const handlers={};
handlers['study']=async(s,m,ctx)=>make('study',`Build a focused study session: choose one topic, set a 25-minute block, remove distractions, then review errors.`).execute(s,m,ctx);
handlers['revision']=async(s,m,ctx)=>make('revision',`Revision cycle: recall from memory → check notes → correct errors → retest tomorrow.`).execute(s,m,ctx);
handlers['flashcard']=async(s,m,ctx)=>make('flashcard',`Create one card with a single question on the front and a concise answer on the back.`).execute(s,m,ctx);
handlers['flashcards']=async(s,m,ctx)=>make('flashcards',`Use short cards, one fact per card, and mix easy with difficult items.`).execute(s,m,ctx);
handlers['timetable']=async(s,m,ctx)=>make('timetable',`Plan blocks around school, sleep, meals and breaks; place difficult subjects when you are most alert.`).execute(s,m,ctx);
handlers['pomodoro']=async(s,m,ctx)=>make('pomodoro',`25 minutes focus + 5 minutes break; after four rounds take a longer break.`).execute(s,m,ctx);
handlers['focus']=async(s,m,ctx)=>make('focus',`Start with one measurable task and keep the phone/distractions away for the focus block.`).execute(s,m,ctx);
handlers['exam']=async(s,m,ctx)=>make('exam',`Check syllabus, past questions, weak topics, timing and required materials.`).execute(s,m,ctx);
handlers['examplan']=async(s,m,ctx)=>make('examplan',`7-day plan: diagnose → revise weak areas → practice → review mistakes → timed paper → light review → rest.`).execute(s,m,ctx);
handlers['essay']=async(s,m,ctx)=>make('essay',`Structure: thesis, clear paragraphs with evidence, explanation and a concise conclusion.`).execute(s,m,ctx);
handlers['summary']=async(s,m,ctx)=>make('summary',`Reduce a topic to key ideas, definitions, formulas and one example.`).execute(s,m,ctx);
handlers['notes']=async(s,m,ctx)=>make('notes',`Use headings, keywords, diagrams and short explanations instead of copying full pages.`).execute(s,m,ctx);
handlers['notemaker']=async(s,m,ctx)=>make('notemaker',`Prompt: Topic / Definition / Key points / Example / Common mistake / Self-test.`).execute(s,m,ctx);
handlers['definition']=async(s,m,ctx)=>make('definition',`Give the term and explain it in simple language, then add one example.`).execute(s,m,ctx);
handlers['explain']=async(s,m,ctx)=>make('explain',`Explain the idea in three layers: simple version, technical version, worked example.`).execute(s,m,ctx);
handlers['simplify']=async(s,m,ctx)=>make('simplify',`Replace jargon with everyday words while preserving the important meaning.`).execute(s,m,ctx);
handlers['memorize']=async(s,m,ctx)=>make('memorize',`Use retrieval practice, spaced repetition, associations and frequent self-testing.`).execute(s,m,ctx);
handlers['mnemonic']=async(s,m,ctx)=>make('mnemonic',`Create an acronym or vivid association from the supplied key terms.`).execute(s,m,ctx);
handlers['activerecall']=async(s,m,ctx)=>make('activerecall',`Close the notes and answer: What? Why? How? Example? Common mistake?`).execute(s,m,ctx);
handlers['spacedrepetition']=async(s,m,ctx)=>make('spacedrepetition',`Review after increasing intervals such as 1 day, 3 days, 7 days and 14 days.`).execute(s,m,ctx);
handlers['pastpaper']=async(s,m,ctx)=>make('pastpaper',`Attempt under time limits, mark honestly, categorize mistakes and redo weak questions.`).execute(s,m,ctx);
handlers['markscheme']=async(s,m,ctx)=>make('markscheme',`Match each answer point to the required idea; do not add irrelevant material.`).execute(s,m,ctx);
handlers['grade']=async(s,m,ctx)=>make('grade',`Grade boundaries vary by exam board; provide your board if you need a specific boundary.`).execute(s,m,ctx);
handlers['gpa']=async(s,m,ctx)=>make('gpa',`GPA depends on the institution scale; enter course grades and credits before calculating.`).execute(s,m,ctx);
handlers['percentage']=async(s,m,ctx)=>make('percentage',`Use: percentage = score ÷ total × 100.`).execute(s,m,ctx);
handlers['fraction']=async(s,m,ctx)=>make('fraction',`Reduce numerator and denominator by their greatest common divisor.`).execute(s,m,ctx);
handlers['ratio']=async(s,m,ctx)=>make('ratio',`Divide all terms by their greatest common factor; keep units consistent.`).execute(s,m,ctx);
handlers['algebra']=async(s,m,ctx)=>make('algebra',`Simplify expressions, isolate the unknown, then verify by substitution.`).execute(s,m,ctx);
handlers['geometry']=async(s,m,ctx)=>make('geometry',`List known angles/lengths, choose the correct theorem/formula and show units.`).execute(s,m,ctx);
handlers['trigonometry']=async(s,m,ctx)=>make('trigonometry',`SOH-CAH-TOA for right triangles; check whether the calculator is in degrees or radians.`).execute(s,m,ctx);
handlers['calculus']=async(s,m,ctx)=>make('calculus',`Differentiate for rates of change; integrate for accumulated change/area.`).execute(s,m,ctx);
handlers['statistics']=async(s,m,ctx)=>make('statistics',`Describe centre, spread, distribution and sample size; distinguish correlation from causation.`).execute(s,m,ctx);
handlers['probability']=async(s,m,ctx)=>make('probability',`Probability is between 0 and 1; use complements and multiplication/addition rules carefully.`).execute(s,m,ctx);
handlers['vectors']=async(s,m,ctx)=>make('vectors',`Separate magnitude and direction; add components and check signs.`).execute(s,m,ctx);
handlers['mechanics']=async(s,m,ctx)=>make('mechanics',`Draw a force diagram, choose axes, write equations and check units.`).execute(s,m,ctx);
handlers['electricity']=async(s,m,ctx)=>make('electricity',`For circuits use V=IR, P=VI and conservation rules; state units.`).execute(s,m,ctx);
handlers['waves']=async(s,m,ctx)=>make('waves',`Use v=fλ and distinguish amplitude, frequency, wavelength and speed.`).execute(s,m,ctx);
handlers['organic']=async(s,m,ctx)=>make('organic',`Focus on functional groups, structures, naming, reactions and conditions.`).execute(s,m,ctx);
handlers['inorganic']=async(s,m,ctx)=>make('inorganic',`Compare ions, periodic trends, bonding, reactions and observations.`).execute(s,m,ctx);
handlers['mole']=async(s,m,ctx)=>make('mole',`Use n=m/M and keep molar mass units consistent.`).execute(s,m,ctx);
handlers['acids']=async(s,m,ctx)=>make('acids',`pH measures acidity; strong/weak describes ionization, not concentration alone.`).execute(s,m,ctx);
handlers['bases']=async(s,m,ctx)=>make('bases',`Bases accept protons or provide hydroxide in common aqueous models.`).execute(s,m,ctx);
handlers['cells']=async(s,m,ctx)=>make('cells',`Know organelles, membranes, transport, cell division and energy processes.`).execute(s,m,ctx);
handlers['respiration']=async(s,m,ctx)=>make('respiration',`Aerobic respiration releases usable energy from glucose using oxygen; know the main stages.`).execute(s,m,ctx);
handlers['photosynthesis']=async(s,m,ctx)=>make('photosynthesis',`Plants convert light energy into chemical energy; learn reactants, products and limiting factors.`).execute(s,m,ctx);
handlers['ecology']=async(s,m,ctx)=>make('ecology',`Study populations, communities, food webs, cycles, habitats and human impacts.`).execute(s,m,ctx);
handlers['genetics']=async(s,m,ctx)=>make('genetics',`Learn genes, alleles, genotype, phenotype, inheritance patterns and variation.`).execute(s,m,ctx);
handlers['evolution']=async(s,m,ctx)=>make('evolution',`Variation plus selection across generations can change populations over time.`).execute(s,m,ctx);
handlers['anatomy']=async(s,m,ctx)=>make('anatomy',`Study body structures by system and connect each structure to its function.`).execute(s,m,ctx);
handlers['physiology']=async(s,m,ctx)=>make('physiology',`Focus on how body systems operate and maintain internal balance.`).execute(s,m,ctx);
handlers['microbiology']=async(s,m,ctx)=>make('microbiology',`Compare bacteria, viruses, fungi and protozoa; learn transmission and prevention.`).execute(s,m,ctx);
handlers['astronomy']=async(s,m,ctx)=>make('astronomy',`Know stars, planets, orbits, spectra, gravity and stellar life cycles.`).execute(s,m,ctx);
handlers['geology']=async(s,m,ctx)=>make('geology',`Study rocks, minerals, plate tectonics, erosion and geological time.`).execute(s,m,ctx);
handlers['geography']=async(s,m,ctx)=>make('geography',`Connect physical processes, human systems, maps, data and case studies.`).execute(s,m,ctx);
handlers['history']=async(s,m,ctx)=>make('history',`Build a timeline, identify causes/consequences and distinguish primary from secondary evidence.`).execute(s,m,ctx);
handlers['government']=async(s,m,ctx)=>make('government',`Learn institutions, constitutions, rights, elections and how laws are made in your jurisdiction.`).execute(s,m,ctx);
handlers['economics']=async(s,m,ctx)=>make('economics',`Separate scarcity, incentives, markets, costs, benefits and macroeconomic indicators.`).execute(s,m,ctx);
handlers['commerce']=async(s,m,ctx)=>make('commerce',`Study trade, business ownership, markets, finance and customer relationships.`).execute(s,m,ctx);
handlers['accounting']=async(s,m,ctx)=>make('accounting',`Use the accounting equation and classify transactions consistently.`).execute(s,m,ctx);
handlers['literature']=async(s,m,ctx)=>make('literature',`Analyze theme, character, language, structure, context and evidence.`).execute(s,m,ctx);
handlers['grammar']=async(s,m,ctx)=>make('grammar',`Identify parts of speech, sentence structure, agreement, tense and punctuation.`).execute(s,m,ctx);
handlers['vocabulary']=async(s,m,ctx)=>make('vocabulary',`Learn meaning, pronunciation, context, synonyms and an example sentence.`).execute(s,m,ctx);
handlers['reading']=async(s,m,ctx)=>make('reading',`Preview headings, ask questions, read actively and summarize from memory.`).execute(s,m,ctx);
handlers['writing']=async(s,m,ctx)=>make('writing',`Plan before drafting, use clear paragraphs, evidence and revision passes.`).execute(s,m,ctx);
handlers['coding']=async(s,m,ctx)=>make('coding',`Break the problem down, define inputs/outputs, implement small steps and test edge cases.`).execute(s,m,ctx);
handlers['javascript']=async(s,m,ctx)=>make('javascript',`Study variables, functions, arrays, objects, async code, modules and error handling.`).execute(s,m,ctx);
handlers['html']=async(s,m,ctx)=>make('html',`Use semantic elements, accessible labels, valid nesting and meaningful structure.`).execute(s,m,ctx);
handlers['css']=async(s,m,ctx)=>make('css',`Use layout, responsive design, reusable classes, spacing and accessible contrast.`).execute(s,m,ctx);
handlers['python']=async(s,m,ctx)=>make('python',`Practice variables, functions, collections, modules, exceptions and file handling.`).execute(s,m,ctx);
handlers['algorithms']=async(s,m,ctx)=>make('algorithms',`Define complexity, choose data structures, test edge cases and prove assumptions.`).execute(s,m,ctx);
handlers['database']=async(s,m,ctx)=>make('database',`Model entities and relationships, use keys and constraints, then query with care.`).execute(s,m,ctx);
handlers['cybersecurity']=async(s,m,ctx)=>make('cybersecurity',`Learn authentication, least privilege, input validation, secure storage and threat modeling.`).execute(s,m,ctx);
handlers['ai']=async(s,m,ctx)=>make('ai',`Study data, models, evaluation, bias, overfitting and responsible deployment.`).execute(s,m,ctx);
handlers['robotics']=async(s,m,ctx)=>make('robotics',`Combine sensing, control, actuation and feedback loops.`).execute(s,m,ctx);
handlers['engineering']=async(s,m,ctx)=>make('engineering',`Define requirements, constraints, trade-offs, testing and documentation.`).execute(s,m,ctx);
handlers['architecture']=async(s,m,ctx)=>make('architecture',`Consider users, structure, site constraints, materials and clear drawings.`).execute(s,m,ctx);
handlers['research']=async(s,m,ctx)=>make('research',`Question → sources → evidence → analysis → limitations → conclusion.`).execute(s,m,ctx);
handlers['citation']=async(s,m,ctx)=>make('citation',`Record author, title, date and URL/identifier while researching so sources are traceable.`).execute(s,m,ctx);
handlers['plagiarism']=async(s,m,ctx)=>make('plagiarism',`Paraphrase genuinely, cite ideas and quote only when exact wording matters.`).execute(s,m,ctx);
handlers['labreport']=async(s,m,ctx)=>make('labreport',`Use aim, hypothesis, variables, method, results, analysis, errors and conclusion.`).execute(s,m,ctx);
handlers['project']=async(s,m,ctx)=>make('project',`Define scope, milestones, risks, deliverables and acceptance criteria.`).execute(s,m,ctx);
handlers['presentation']=async(s,m,ctx)=>make('presentation',`One idea per slide, readable text, strong evidence and rehearsal.`).execute(s,m,ctx);
handlers.percentage=async(s,m,{args,reply})=>{const a=+args[0],b=+args[1];if(!Number.isFinite(a)||!Number.isFinite(b)||b===0)return reply('Use .percentage score total');return reply(`${(a/b*100).toFixed(2)}%`)};
handlers.fraction=async(s,m,{args,reply})=>{let a=+args[0],b=+args[1];if(!Number.isInteger(a)||!Number.isInteger(b)||b===0)return reply('Use .fraction numerator denominator');const g=(x,y)=>y?g(y,x%y):Math.abs(x);const d=g(a,b);return reply(`${a/d}/${b/d}`)};
handlers.gpa=async(s,m,{args,reply})=>{const a=args.map(Number).filter(Number.isFinite);if(!a.length)return reply('Use .gpa 4 3 3 4');return reply(`Average GPA: ${(a.reduce((x,y)=>x+y,0)/a.length).toFixed(2)}`)};
module.exports=Object.keys(handlers).map(name=>({name,category:'Education',desc:`Dedicated ${name} education function`,usage:`.${name} [topic]`,execute:handlers[name]}));
