const crypto=require('node:crypto');
const c=(name,desc,fn)=>({name,alias:[],category:'Utility',desc,usage:`.${name}`,execute:async(s,m,{args,reply})=>reply(fn(args,m))});
const pick=a=>a[Math.floor(Math.random()*a.length)];
module.exports=[
 c('uuid','Generate a random identifier',()=>crypto.randomUUID()),
 c('timestamp','Show a Unix timestamp',()=>String(Date.now())),
 c('iso','Show an ISO timestamp',()=>new Date().toISOString()),
 c('percent','Calculate a percentage',a=>{const [x,y]=a.map(Number);return Number.isFinite(x)&&Number.isFinite(y)?`${(x/y*100).toFixed(2)}%`:'Usage: .percent part total'}),
 c('average','Average numbers',a=>{const n=a.map(Number).filter(Number.isFinite);return n.length?(n.reduce((x,y)=>x+y,0)/n.length).toFixed(2):'Provide numbers.'}),
 c('sum','Sum numbers',a=>String(a.map(Number).filter(Number.isFinite).reduce((x,y)=>x+y,0))),
 c('min','Find the minimum number',a=>String(Math.min(...a.map(Number).filter(Number.isFinite)))),
 c('max','Find the maximum number',a=>String(Math.max(...a.map(Number).filter(Number.isFinite)))),
 c('sort','Sort numbers',a=>a.map(Number).filter(Number.isFinite).sort((x,y)=>x-y).join(', ')),
 c('dedupe','Remove duplicate words',a=>[...new Set(a)].join(' ')),
 c('titlecase','Title-case text',a=>a.join(' ').replace(/\b\w/g,x=>x.toUpperCase())),
 c('slug','Create a URL slug',a=>a.join('-').toLowerCase().replace(/[^a-z0-9-]+/g,'').replace(/-+/g,'-')),
 c('urlencode','URL encode text',a=>encodeURIComponent(a.join(' '))),
 c('urldecode','URL decode text',a=>{try{return decodeURIComponent(a.join(' '))}catch{return 'Invalid URL encoding.'}}),
 c('binary','Convert text to binary',a=>Buffer.from(a.join(' ')).toString('2')),
 c('hex','Convert text to hexadecimal',a=>Buffer.from(a.join(' ')).toString('hex')),
 c('unhex','Decode hexadecimal',a=>Buffer.from(a.join(''),'hex').toString()),
 c('charcount','Count letters',a=>(a.join(' ').match(/[A-Za-z]/g)||[]).length.toString()),
 c('vowels','Count vowels',a=>(a.join(' ').match(/[aeiou]/gi)||[]).length.toString()),
 c('palindrome','Check if text is a palindrome',a=>{const x=a.join('').toLowerCase().replace(/\W/g,'');return x===x.split('').reverse().join('')?'Yes':'No'}),
 c('randomcolor','Generate a color',()=>`#${Math.floor(Math.random()*0xffffff).toString(16).padStart(6,'0')}`),
 c('randomhex','Generate a hex token',()=>Math.random().toString(16).slice(2,10)),
 c('yesno','Choose yes or no',()=>pick(['Yes','No'])),
 c('affirm','Generate an affirmation',()=>pick(['I can improve one step at a time.','My questions help me learn.'])),
 c('status','Show a compact status',()=>`NODAX online · ${new Date().toLocaleTimeString()}`),
 c('whoami','Show current sender',(_,m)=>m.sender||'unknown'),
 c('chatid','Show chat ID',(_,m)=>m.chat),
 c('sender','Show sender ID',(_,m)=>m.sender||'unknown'),
 c('groupcheck','Check group context',(_,m)=>m.isGroup?'This is a group.':'This is a private chat.'),
 c('admincheck','Check admin context',(_,m)=>m.isAdmin?'You are an admin.':'You are not an admin.'),
 c('botadmincheck','Check NODAX admin context',(_,m)=>m.isBotAdmin?'NODAX is an admin.':'NODAX is not an admin.'),
 c('line','Create a divider',a=>`──────── ${a.join(' ')||'NODAX'} ────────`),
 c('box','Create a rich message box',a=>`╭────────────╮\n│ ${a.join(' ').slice(0,30)||'NODAX'}\n╰────────────╯`),
 c('bullet','Format a bullet list',a=>a.join(' ').split(',').map(x=>`• ${x.trim()}`).join('\n')),
 c('numbered','Format a numbered list',a=>a.join(' ').split(',').map((x,i)=>`${i+1}. ${x.trim()}`).join('\n')),
 c('notice','Create a notice card',a=>`🔔 *NOTICE*\n\n${a.join(' ')||'No notice.'}`)
];
