const axios = require('axios');
const http = axios.create({ timeout: 15000, headers: { 'User-Agent': 'NODAX/1.0 by Musteqeem', Accept: 'application/json' } });
async function weather(place = 'Lagos') { const geo = await http.get('https://geocoding-api.open-meteo.com/v1/search', { params: { name: place, count: 1, language: 'en', format: 'json' } }); const x = geo.data?.results?.[0]; if (!x) return 'Location not found.'; const w = await http.get('https://api.open-meteo.com/v1/forecast', { params: { latitude: x.latitude, longitude: x.longitude, current: 'temperature_2m,relative_humidity_2m,apparent_temperature,wind_speed_10m,weather_code', timezone: 'auto' } }); const c=w.data.current; return `🌤️ ${x.name}, ${x.country}\n${c.temperature_2m}°C (feels ${c.apparent_temperature}°C)\nHumidity ${c.relative_humidity_2m}% · Wind ${c.wind_speed_10m} km/h\nWeather code ${c.weather_code}`; }
async function wiki(topic) { const r=await http.get(`https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(String(topic).trim().replace(/\s+/g,'_'))}`); return `📚 *${r.data.title}*\n\n${r.data.extract || 'No summary found.'}\n\n${r.data.content_urls?.desktop?.page || ''}`; }
async function define(word) { const r=await http.get(`https://api.dictionaryapi.dev/api/v2/entries/en/${encodeURIComponent(String(word).trim())}`); const e=r.data[0],m=e.meanings?.[0],d=m?.definitions?.[0]; return `📖 *${e.word}* (${m?.partOfSpeech || 'word'})\n${d?.definition || 'No definition.'}${d?.example ? `\nExample: ${d.example}` : ''}`; }
async function joke() { const r=await http.get('https://v2.jokeapi.dev/joke/Any?type=single&safe-mode'); return `😄 ${r.data.joke}`; }
async function country(name) { const r=await http.get(`https://restcountries.com/v3.1/name/${encodeURIComponent(String(name).trim())}`); const c=r.data[0]; return `🌍 *${c.name.common}*\nCapital: ${c.capital?.[0] || 'n/a'}\nPopulation: ${c.population?.toLocaleString() || 'n/a'}\nRegion: ${c.region}`; }
async function github(repo) { const r=await http.get(`https://api.github.com/repos/${String(repo).replace(/^https?:\/\/github\.com\//,'').replace(/\/$/,'')}`); return `🐙 *${r.data.full_name}*\n⭐ ${r.data.stargazers_count} · Issues ${r.data.open_issues_count}\n${r.data.description || ''}`; }
module.exports = { weather, wiki, define, joke, country, github };
