const { getTargets, formatJid, inputText } = require('../../core/helpers');
const c=(name,desc,execute,alias=[],extra={})=>({name,alias,category:'Group',desc,usage:`.${name}`,execute,...extra});
function needBot(m,reply){if(!m.isBotAdmin)return reply('❌ Make NODAX a group admin first.');}
module.exports=[
 c('ginfo','Show group metadata',async(s,m,{reply})=>reply(`📊 *${m.metadata.subject}*\nMembers: ${m.metadata.participants.length}\nAdmins: ${m.metadata.participants.filter(x=>x.admin).length}\nJID: ${m.chat}`),['groupinfo'],{groupOnly:true}),
 c('admins','List group admins',async(s,m,{reply})=>{const a=m.metadata.participants.filter(x=>x.admin);return reply(a.map(x=>`• ${formatJid(x.id)}`).join('\n')||'No admins found.',{mentions:a.map(x=>x.id)})},['listadmins'],{groupOnly:true}),
 c('tagall','Mention every member',async(s,m,{args,reply})=>{const p=m.metadata.participants.map(x=>x.id);return reply(`📣 ${inputText(args,m)||'Attention everyone'}\n\n${p.map(x=>formatJid(x)).join(' ')}`,{mentions:p})},['everyone','mentionall'],{groupOnly:true,adminOnly:true}),
 c('listmembers','List members',async(s,m,{reply})=>reply(m.metadata.participants.map((x,i)=>`${i+1}. ${formatJid(x.id)}${x.admin?' 👑':''}`).join('\n'),{mentions:m.metadata.participants.map(x=>x.id)}),['members'],{groupOnly:true}),
 c('promote','Promote a member',async(s,m,{args,reply})=>{const t=getTargets(m,args)[0];if(!t)return reply('Mention, quote, or provide a number.');await s.groupParticipantsUpdate(m.chat,[t],'promote');return reply(`✅ Promoted ${formatJid(t)}.`,{mentions:[t]})},[],{groupOnly:true,adminOnly:true,botAdmin:true}),
 c('demote','Demote a member',async(s,m,{args,reply})=>{const t=getTargets(m,args)[0];if(!t)return reply('Mention, quote, or provide a number.');await s.groupParticipantsUpdate(m.chat,[t],'demote');return reply(`✅ Demoted ${formatJid(t)}.`,{mentions:[t]})},[],{groupOnly:true,adminOnly:true,botAdmin:true}),
 c('kick','Remove a member',async(s,m,{args,reply})=>{const t=getTargets(m,args)[0];if(!t)return reply('Mention, quote, or provide a number.');await s.groupParticipantsUpdate(m.chat,[t],'remove');return reply(`✅ Removed ${formatJid(t)}.`,{mentions:[t]})},['remove','ban'],{groupOnly:true,adminOnly:true,botAdmin:true}),
 c('add','Add a member by number',async(s,m,{args,reply})=>{const n=String(args[0]||'').replace(/\D/g,'');if(n.length<7)return reply('Usage: .add 2348012345678');await s.groupParticipantsUpdate(m.chat,[`${n}@s.whatsapp.net`],'add');return reply(`✅ Add request sent for +${n}.`)},[],{groupOnly:true,adminOnly:true,botAdmin:true}),
 c('mute','Restrict messages to admins',async(s,m,{reply})=>{await s.groupSettingUpdate(m.chat,'announcement');return reply('🔒 Group locked. Only admins can message.')},['lock'],{groupOnly:true,adminOnly:true,botAdmin:true}),
 c('unmute','Allow all members to message',async(s,m,{reply})=>{await s.groupSettingUpdate(m.chat,'not_announcement');return reply('🔓 Group opened for members.')},['unlock'],{groupOnly:true,adminOnly:true,botAdmin:true}),
 c('setsubject','Change group subject',async(s,m,{args,reply})=>{const x=inputText(args,m);if(!x)return reply('Provide a subject.');await s.groupUpdateSubject(m.chat,x);return reply('✅ Subject updated.')},[],{groupOnly:true,adminOnly:true,botAdmin:true}),
 c('setdesc','Change group description',async(s,m,{args,reply})=>{const x=inputText(args,m);if(!x)return reply('Provide a description.');await s.groupUpdateDescription(m.chat,x);return reply('✅ Description updated.')},[],{groupOnly:true,adminOnly:true,botAdmin:true}),
 c('grouplink','Get invite link',async(s,m,{reply})=>reply(`https://chat.whatsapp.com/${await s.groupInviteCode(m.chat)}`),['invite'],{groupOnly:true,adminOnly:true,botAdmin:true}),
 c('revoke','Revoke group invite',async(s,m,{reply})=>{await s.groupRevokeInvite(m.chat);return reply('✅ Group invite revoked.')},[],{groupOnly:true,adminOnly:true,botAdmin:true}),
 c('welcome','Toggle welcome messages',async(s,m,{args,reply,store})=>{const v=String(args[0]||'status').toLowerCase();if(v==='on'||v==='off')store.group(m.chat).welcome=v==='on';store.save();return reply(`Welcome: ${store.group(m.chat).welcome?'ON':'OFF'}`)},[],{groupOnly:true,adminOnly:true}),
 c('goodbye','Toggle goodbye messages',async(s,m,{args,reply,store})=>{const v=String(args[0]||'status').toLowerCase();if(v==='on'||v==='off')store.group(m.chat).goodbye=v==='on';store.save();return reply(`Goodbye: ${store.group(m.chat).goodbye?'ON':'OFF'}`)},[],{groupOnly:true,adminOnly:true}),
 c('setwelcome','Set welcome template',async(s,m,{args,reply,store})=>{store.group(m.chat).welcomeText=inputText(args,m)||'Welcome @user to @group!';store.save();return reply('✅ Welcome template saved. Use @user, @group, @count.')},[],{groupOnly:true,adminOnly:true}),
 c('setgoodbye','Set goodbye template',async(s,m,{args,reply,store})=>{store.group(m.chat).goodbyeText=inputText(args,m)||'Goodbye @user.';store.save();return reply('✅ Goodbye template saved.')},[],{groupOnly:true,adminOnly:true}),
 c('poll','Create a poll',async(s,m,{args,reply})=>{const [q,...opts]=inputText(args,m).split('|').map(x=>x.trim());if(!q||opts.length<2)return reply('Usage: .poll question | option 1 | option 2');return s.sendMessage(m.chat,{poll:{name:q,values:opts,selectableCount:1}},{quoted:m.raw})},[],{groupOnly:true}),
 c('announce','Send an admin announcement',async(s,m,{args,reply})=>reply(`📢 *ANNOUNCEMENT*\n\n${inputText(args,m)||'No announcement text.'}`),[],{groupOnly:true,adminOnly:true}),
 c('groupmode','Show group mode',async(s,m,{reply,store})=>{const g=store.group(m.chat);return reply(`Welcome ${g.welcome?'ON':'OFF'} · Goodbye ${g.goodbye?'ON':'OFF'} · Locked ${g.locked?'ON':'OFF'}`)},[],{groupOnly:true}),
 c('clearwarn','Clear a member warning record',async(s,m,{args,reply,store})=>{const t=getTargets(m,args)[0];if(!t)return reply('Mention or quote a member.');store.clearWarnings(m.chat,t);return reply(`✅ Cleared warnings for ${formatJid(t)}.`,{mentions:[t]})},[],{groupOnly:true,adminOnly:true})
];
